language: node_js

cache: yarn

node_js:
  - 8
  - 10

before_install:
  - npm i -g yarn

script:
  - yarn lint
  - yarn build
  - yarn test

# Environment variables marked with `secure` should be securely encrypted as described at:
# https://docs.travis-ci.com/user/environment-variables/#encrypting-environment-variables

notifications:
  slack:
    rooms:
      - secure: XHV3esqW1jjmCKskz8sOH+G/L0cAFv1c2JKqjDWVCqim2uXxI6hKZjuz7tpaq44orSS/7+LSgJMXjv92JoFHSz0zPj3SKcHS0w2h1rfdfpTqS6QUkJ5PwrfEDzOKyNdL7KzoRwhpnnBLQBOa9Oli55VQM0ja8eaX1sU3iMWHV0OWVdeXQKKYkLn36WAGucQRyuLIAKziCds1McWJFPUsrmfqoW8f2mNRbvpUdcJpgxMctWUATebUAY2U9vor/bJTxuirn6qsf7q3PfTJQJ3819TfHAvrdEBRtmP7VHEi1aTJtiIDHAakMd2aBINsty8KXt9scdGwACuEi7odK+6s4oigwjVgkhek8e3UWga29c4k1rjZxE0y+OiNQBISufWkzjM92rUkz7qeSa+v8m8AjcfNhtpa3MRSbeXiQO9gMpojMAHjGxelSPlFrklTpDPRfrlj49LSKE1vZSqz9NLAKI61D7s8GQS7Ul2+PVSD3eTFk4vzd+wqtYti398p2s+hQ8ul8wb4a2SxqiGBG8+CdGyacf5fT1h5h2steJkpU5TFYGtcPgELshVLELECQChZFANF93qO5KL9yNBShBIuUsWc9KskOqaFwoNAVkaqIghuN+Dwpaj7Gfc6PxElW1TURZzxoOAolCczZusLbiD+XOlNdXF3ICkocCA9R33/rbM=
    on_success: change
    on_failure: always

env:
  global:
    - secure: n+FBKBJn+wB6WZPwnL8EMmO/lyki7cT3ojeHS1IZMYnxjiy3Dvzj9P+jaoTuz2CEcSe+EiRTqCorQF7hnmWlX4AxopZBvuL9ogYFnCQlamTegyVmrV9y/PN0SsHYblC5D6x7iYQCDQLAItgdH7s3bHq6Lvsr9MIbHiGVFNCnzGZIcAZX/H4PWApvRKr+cpuq3bKefj+0zydAYx3lo96iALxD/s3giZDl6K0i6vefrruGNPaOOJXHUj2SLonDKgfX0V7xqYNv0dWXICIRThnb9XSIgdbBzwru0DtPRP8QR/QmAbav3oEuw6qpUYgdtoYfeebCeJpUmX2jUe69S2Z6UduTxY6iK4b9hEYasg0BSj2xqgG77sVBq8l5D4u2k+Y3HbBy1EbXBFO9oMGCUATKgvXAPyjrhWSpzV2FNNqvefj9ZyONpHmY9SFSijqjgAOxhTsZmbGPkZ/r3Y9quOoDz45MySF5Fd13kuO6rRsCVLHXjrj+zAOmJqvoegt2dW4eECYfIizigytIzwqVyst0bDfeJQ/Yxos0RfW1oCLDb+RnoVCLs/iHxAN4UsHpfEoLLAJ18Pzhs0paCtVMoOJiQja+8bd3I3U0qUIGqIgGG9I7QDCO7kky+jnozBxOBBr5GJxb1MQWfRUBnosApV4CAOQe38AEnhwMbMOMCxC+hs8=
    - secure: RRXY5SwKXQO0I/3p5UpCKBbkwN6jjHX4DvGzWDHwcrNj6MMUjL3Kl2s5zCE90tJ66ISKj9x9ZhLpzD3mPCpZjG/cwFGattZ3tzoHlM6tlLztas6mHgJy+yMrjXLSyKiM5ce/b/K00IjOUhMEc8eaYHXMK8WsJDQRo0NJWsP/fhgGUUAh55ecEc+AUECp365bwBDYUHt+knInUtLZre85l2ymn7k5QcKeUBHKwAiP4DaUxhL2YM2YiYao806IYttD6bjel9tEnmZi+FUvzNdUzZNzfFacRlSjqMJ+XR34wxkErtw/drr9yy9RORhQmP2yjEa0f1T+VQdDcZnhup1FyNCNBVYNdP/Nr4Rvo7txLliUOHTuzuehMw0JFGjjHJT6fJWqsHWiY8MP+YD9hkNASPgWErQWa3Xy5hYQ/PLl6csEaAe9duRfVSyt+hrJVrFNmfA0LADKZV+61a26ce6GHSDcQMwCtYY8QW2M3Q6j0PYI30yvqD61Wa5LMI9WqwdUZIYCfjRKpC3JvUqF0g4HjjNFxW6D7pfFxkXwWa4t2nv/CgLJleMtaV0SvMByNvy/zCTb6tGM99Thbyp9nmMhgcXL1158JDOdsUcEK6OYCKmcefQGuefgJgeX3JOzxEsDUI9/g/oMamjZ+vd0tvaPdQqvGtT07xgQtABrPUQJp44=
    - secure: lwTRm9scTABTjFg34i9eK4Xptujr3/xgW06FipDKk+3MKAY/aV/IQSrSV8VPjFeWYYNG5w8N6650Y7d0KVpgupPfIwtHI0voMpjV6uZVxty67VZBhcKvupc7WgZptpZLmr0P2L2hfCeWPNhhugs9pJWUEdQE8kSjjC/k6NJ3Or6SqKZjgDSftE0+LZAYoNRV7Gvi1z3Wzssa2BVI3XVgbyqxVQ3ng0MDysGTme0vGurNVZoNpSjADNFVOdAksbHm9crc40SZKj3G33XTgRPnvFILoTzm2mwh2vqsrboY902rLp+rDHPy66Wpa4R8U0pr4uizz0dJGU6qMPowcgEalzaRUMGMiULBQWjTUj4ZkIIz+J0CCPj6Wncp+ogSUt27WE56mE9Bffh0am5+TU7dGNbEbp7jfQNkS7PBTFXFcDwVRh2pVWdFNfxjzD6mgSRiuqxOxTVe0c9M9LMCuOblTwRDrG8ak6DG9B/oxBgdjEzxr4eh+meaad8hvkDkM7Oa+PaYX2iDEGq8QafAyPuRXQQeoC9NZHmMWteoDZjGwDHEcsq5hAAphbDgGZzEUXgNIRgzQwqlEW3AQtrehfXOhwrASXgpPFVZhbGtarj54DcOMXv5u+XLZ1DrqqIjK++69ej4MN380o1kaKvsZKfaZCDnHutTcC3/k4mU6AXmuPU=
    - export GIT_AUTHOR_NAME="esg-bot"
    - export GIT_AUTHOR_EMAIL="tech@endemolshine.com"
    - export GIT_COMMITTER_NAME="esg-bot"
    - export GIT_COMMITTER_EMAIL="tech@endemolshine.com"

jobs:
  include:
    - stage: coverage
      if: type != pull_request
      before_script:
        - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
        - chmod +x ./cc-test-reporter
        - ./cc-test-reporter before-build
      after_script:
        - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
      after_success:
        - yarn global add codecov
        - codecov
    - stage: release
      if: branch = master AND type != pull_request
      after_success:
        - yarn semantic-release
        - git clone https://${GH_TOKEN}@github.com/$TRAVIS_REPO_SLUG.git $TRAVIS_REPO_SLUG
        - cd $TRAVIS_REPO_SLUG
        - git fetch --all
        - git merge origin/master
        - git push
