service:
  name: serverless-slack-notifier

plugins:
- serverless-webpack

provider:
  name: aws
  runtime: nodejs8.10
  region: us-east-1

  environment:
    SLACK_HOOK_URL: ${env:SLACK_HOOK_URL}

iamRoleStatements:
  - Effect: "Allow"
    Action:
    - "SNS:Publish"
    Resource:
      Ref: SNSTopicSlackAlarmsTopic

functions:
  postErrorsToSlack: ${file(services/sns/PostErrorsToSlack/function.yml)}

resources:
  Outputs: ${file(conf/outputs.yml)}
